// apps/frontend/src/features/home/components/HomeSalaryBenchmark.vue
<script lang="ts" setup>
import { computed, ref } from 'vue';

import { toWanInt } from '../../../utils/format';
import InfoHint from '../../methodology/components/InfoHint.vue';
import { useHomeStore } from '../useHomeStore';

defineProps<{ loading: boolean }>();

const store = useHomeStore();

const salaryUnit = ref<'month' | 'year'>('year');

const benchmarkTags: Record<string, string> = {
  median: 'PR50',
  high: 'PR75',
  top: 'PR88',
};

const benchmarkLabels: Record<string, string> = {
  median: '中位數',
  high: '高薪',
  top: '頂薪',
};

const weightedRatioText = computed(() => {
  const ratio = store.salaryWeightedRatios[salaryUnit.value];
  return ratio ? `${ratio} 倍` : '—';
});

const activeBenchmarks = computed(() => {
  const benchmark =
    salaryUnit.value === 'month'
      ? store.salaryBenchmarks.month
      : store.salaryBenchmarks.year;
  return [
    {
      key: 'median',
      value: benchmark['median'],
      position: 50,
    },
    {
      key: 'high',
      value: benchmark['high'],
      position: 75,
    },
    {
      key: 'top',
      value: benchmark['top'],
      position: 88,
    },
  ];
});
</script>

<template>
  <section class="mt-10">
    <div class="mb-4 flex items-baseline justify-between">
      <div
        class="flex items-center gap-1.5 text-xs font-bold tracking-[0.18em] text-[#434653]"
      >
        市場薪資行情
        <InfoHint metric="home.salaryBenchmark" />
      </div>
      <div
        class="flex overflow-hidden rounded-lg border border-[#c9e7f7] text-xs"
      >
        <button
          v-for="opt in [
            { v: 'year', l: '年薪' },
            { v: 'month', l: '月薪' },
          ]"
          :key="opt.v"
          class="cursor-pointer px-3.5 py-1.5 font-bold transition-colors"
          :class="
            salaryUnit === opt.v
              ? 'bg-[#003d92] text-white'
              : 'bg-[#d9f2ff] text-[#434653] hover:bg-[#ceedfd]'
          "
          @click="salaryUnit = opt.v as 'month' | 'year'"
        >
          {{ opt.l }}
        </button>
      </div>
    </div>
    <div
      class="mb-4 inline-flex items-center gap-2 rounded-lg bg-[#f4faff] px-3 py-2"
    >
      <span
        class="text-xs font-bold tracking-wide text-[#434653]"
        >市場加權比率</span
      >
      <span
        class="font-mono text-sm font-black text-[#003d92] tabular-nums"
        >{{ weightedRatioText }}</span
      >
      <InfoHint metric="home.salaryWeightedRatio" />
    </div>
    <div
      v-if="loading"
      class="grid grid-cols-1 gap-3 sm:grid-cols-3"
    >
      <div
        v-for="i in 3"
        :key="i"
        class="flex animate-pulse flex-col rounded-xl bg-white p-5 shadow-[0_24px_40px_rgba(0,31,42,0.06)]"
      >
        <div class="mb-4 flex items-center justify-between">
          <div class="h-4 w-8 rounded bg-[#001f2a]/8" />
          <div class="h-3 w-10 rounded bg-[#001f2a]/8" />
        </div>
        <div
          class="mb-3 h-14 w-32 rounded bg-[#001f2a]/8"
        />
        <div
          class="mb-1.5 h-3 w-full rounded bg-[#001f2a]/8"
        />
        <div
          class="mb-3 h-3 w-4/5 rounded bg-[#001f2a]/8"
        />
        <div
          class="mt-auto h-1.5 w-full rounded-full bg-[#001f2a]/8"
        />
      </div>
    </div>
    <div
      v-else
      class="grid grid-cols-1 gap-3 sm:grid-cols-3"
    >
      <div
        v-for="benchmark in activeBenchmarks"
        :key="benchmark.key"
        class="flex flex-col rounded-xl bg-white p-5 shadow-[0_24px_40px_rgba(0,31,42,0.06)]"
      >
        <div
          class="mb-3 flex items-baseline justify-between"
        >
          <span class="text-sm font-black text-[#001f2a]">{{
            benchmarkLabels[benchmark.key]
          }}</span>
          <span
            class="font-mono text-[10px] tracking-widest text-[#434653]"
          >
            {{ benchmarkTags[benchmark.key] }}
          </span>
        </div>
        <div
          class="leading-[0.95] font-black tracking-[-0.03em] text-[#003d92] tabular-nums"
          style="font-size: 3.25rem"
        >
          {{ toWanInt(benchmark.value) }}
          <span
            class="text-[1.375rem] font-black text-[#434653]"
            >萬</span
          >
        </div>
        <div
          class="mt-3 flex h-1.5 overflow-hidden rounded-full bg-[#d9f2ff]"
        >
          <div
            class="bg-[#003d92] transition-all duration-500"
            :style="{
              width: `${benchmark.position + 1}%`,
            }"
          />
          <div class="w-2 bg-[#fd7700]" />
        </div>
      </div>
    </div>
  </section>
</template>

// apps/frontend/src/features/home/components/HomeSalaryBenchmark.tsx
import { useState } from 'react';

import { toWanInt } from '../../../utils/format';
import { InfoHint } from '../../methodology/components/InfoHint';
import { useHomeData } from '../hooks/useHomeData';

const BENCHMARK_TAGS: Record<string, string> = {
  median: 'PR50',
  high: 'PR75',
  top: 'PR88',
};
const BENCHMARK_LABELS: Record<string, string> = {
  median: '中位數',
  high: '高薪',
  top: '頂薪',
};

export function HomeSalaryBenchmark() {
  const { loading, salaryBenchmarks, salaryWeightedRatios } = useHomeData();
  const [salaryUnit, setSalaryUnit] = useState<'month' | 'year'>('year');

  const ratio = salaryWeightedRatios[salaryUnit];
  const weightedRatioText = ratio ? `${ratio} 倍` : '—';

  const benchmark = salaryBenchmarks[salaryUnit];
  const activeBenchmarks = [
    { key: 'median', value: benchmark.median, position: 50 },
    { key: 'high', value: benchmark.high, position: 75 },
    { key: 'top', value: benchmark.top, position: 88 },
  ];

  return (
    <section className="mt-10">
      <div className="mb-4 flex items-baseline justify-between">
        <div className="flex items-center gap-1.5 text-xs font-bold tracking-[0.18em] text-[#434653]">
          市場薪資行情
          <InfoHint metric="home.salaryBenchmark" />
        </div>
        <div className="flex overflow-hidden rounded-lg border border-[#c9e7f7] text-xs">
          {[
            { v: 'year', l: '年薪' },
            { v: 'month', l: '月薪' },
          ].map(opt => (
            <button
              key={opt.v}
              type="button"
              className={`cursor-pointer px-3.5 py-1.5 font-bold transition-colors ${
                salaryUnit === opt.v
                  ? 'bg-[#003d92] text-white'
                  : 'bg-[#d9f2ff] text-[#434653] hover:bg-[#ceedfd]'
              }`}
              onClick={() => setSalaryUnit(opt.v as 'month' | 'year')}
            >
              {opt.l}
            </button>
          ))}
        </div>
      </div>
      <div className="mb-4 inline-flex items-center gap-2 rounded-lg bg-[#f4faff] px-3 py-2">
        <span className="text-xs font-bold tracking-wide text-[#434653]">
          市場加權比率
        </span>
        <span className="font-mono text-sm font-black text-[#003d92] tabular-nums">
          {weightedRatioText}
        </span>
        <InfoHint metric="home.salaryWeightedRatio" />
      </div>
      {loading ? (
        <div className="grid grid-cols-1 gap-3 sm:grid-cols-3">
          {[0, 1, 2].map(i => (
            <div
              key={i}
              className="flex animate-pulse flex-col rounded-xl bg-white p-5 shadow-[0_24px_40px_rgba(0,31,42,0.06)]"
            >
              <div className="mb-4 flex items-center justify-between">
                <div className="h-4 w-8 rounded bg-[#001f2a]/8" />
                <div className="h-3 w-10 rounded bg-[#001f2a]/8" />
              </div>
              <div className="mb-3 h-14 w-32 rounded bg-[#001f2a]/8" />
              <div className="mb-1.5 h-3 w-full rounded bg-[#001f2a]/8" />
              <div className="mb-3 h-3 w-4/5 rounded bg-[#001f2a]/8" />
              <div className="mt-auto h-1.5 w-full rounded-full bg-[#001f2a]/8" />
            </div>
          ))}
        </div>
      ) : (
        <div className="grid grid-cols-1 gap-3 sm:grid-cols-3">
          {activeBenchmarks.map(b => (
            <div
              key={b.key}
              className="flex flex-col rounded-xl bg-white p-5 shadow-[0_24px_40px_rgba(0,31,42,0.06)]"
            >
              <div className="mb-3 flex items-baseline justify-between">
                <span className="text-sm font-black text-[#001f2a]">
                  {BENCHMARK_LABELS[b.key]}
                </span>
                <span className="font-mono text-[10px] tracking-widest text-[#434653]">
                  {BENCHMARK_TAGS[b.key]}
                </span>
              </div>
              <div
                className="leading-[0.95] font-black tracking-[-0.03em] text-[#003d92] tabular-nums"
                style={{ fontSize: '3.25rem' }}
              >
                {toWanInt(b.value)}
                <span className="text-[1.375rem] font-black text-[#434653]">
                  萬
                </span>
              </div>
              <div className="mt-3 flex h-1.5 overflow-hidden rounded-full bg-[#d9f2ff]">
                <div
                  className="bg-[#003d92] transition-all duration-500"
                  style={{ width: `${b.position + 1}%` }}
                />
                <div className="w-2 bg-[#fd7700]" />
              </div>
            </div>
          ))}
        </div>
      )}
    </section>
  );
}
