// apps/frontend/src/features/home/components/HomePopularTech.tsx
import { KeywordTechRankingCardList } from '../../../components/KeywordTechRankingCardList';
import { InfoHint } from '../../methodology/components/InfoHint';
import { useKeywordTechRanking } from '../hooks/useKeywordTechRanking';

interface HomePopularTechProps {
  ranking: ReturnType<typeof useKeywordTechRanking>;
}

// Receives the shared popular-tech ranking from HomePage so the page can also
// derive the list of techs for HomeHotCombos (mirrors the Vue shared store
// instance).
export function HomePopularTech({ ranking }: HomePopularTechProps) {
  return (
    <KeywordTechRankingCardList
      title="熱門技術"
      items={ranking.items}
      loading={ranking.loading}
      getItems={ranking.getItems}
      moreTo="/techs?mode=popular"
      titleHint={<InfoHint metric="home.popularTech" />}
    />
  );
}

// apps/frontend/src/features/home/components/HomePopularTech.vue
<script lang="ts" setup>
import KeywordTechRankingCardList from '../../../components/KeywordTechRankingCardList.vue';
import InfoHint from '../../methodology/components/InfoHint.vue';
import { useHomeStore } from '../useHomeStore';

const store = useHomeStore();
</script>

<template>
  <KeywordTechRankingCardList
    title="熱門技術"
    :items="store.keywordTechRanking.items"
    :loading="store.keywordTechRanking.loading"
    :get-items="store.keywordTechRanking.getItems"
    :more-to="{
      name: 'techs',
      query: { mode: 'popular' },
    }"
  >
    <template #title-hint>
      <InfoHint metric="home.popularTech" />
    </template>
  </KeywordTechRankingCardList>
</template>
