// apps/frontend/src/features/company/components/CompanyCard.tsx
import { useMemo } from 'react';

import { SupabaseView } from '@codeshore/data-types';

interface CompanyCardProps {
  company: SupabaseView.MvCompany;
  keywordGroups: SupabaseView.MvKeywordGroup[];
  categoryLabelMap: Record<string, string>;
  selectedKeywordGroups?: string[];
  onClick: (companyName: string) => void;
}

const CATEGORY_PRIORITY: Record<string, number> = {
  language: 0,
  framework: 1,
  database: 2,
  library: 3,
  service: 4,
  tool: 5,
};

export function CompanyCard({
  company,
  keywordGroups,
  categoryLabelMap,
  selectedKeywordGroups = [],
  onClick,
}: CompanyCardProps) {
  const { categoryMap, labelMap, countMap } = useMemo(() => {
    const categoryMap = new Map<string, string>();
    const labelMap = new Map<string, string>();
    const countMap = new Map<string, number>();
    for (const m of keywordGroups) {
      categoryMap.set(m.keyword_group, m.category ?? '');
      labelMap.set(m.keyword_group, m.label);
      countMap.set(m.keyword_group, m.count);
    }
    return { categoryMap, labelMap, countMap };
  }, [keywordGroups]);

  const selectedSet = useMemo(
    () => new Set(selectedKeywordGroups),
    [selectedKeywordGroups],
  );

  const groupedKeywordGroups = useMemo(() => {
    const buckets = new Map<string, string[]>();
    for (const kg of company.keyword_groups) {
      const raw = categoryMap.get(kg) ?? '';
      const cat = raw in CATEGORY_PRIORITY ? raw : '';
      if (!buckets.has(cat)) buckets.set(cat, []);
      buckets.get(cat)!.push(kg);
    }
    return [...buckets.entries()]
      .sort(
        ([a], [b]) =>
          (CATEGORY_PRIORITY[a] ?? 6) - (CATEGORY_PRIORITY[b] ?? 6),
      )
      .map(([cat, kgs]) => {
        const sorted = [...kgs].sort(
          (a, b) => (countMap.get(b) ?? 0) - (countMap.get(a) ?? 0),
        );
        return {
          label: categoryLabelMap[cat] ?? '其他',
          items: sorted.slice(0, 5),
          remaining: Math.max(0, sorted.length - 5),
        };
      });
  }, [company.keyword_groups, categoryMap, countMap, categoryLabelMap]);

  let host = '';
  try {
    if (company.company_link) host = new URL(company.company_link).host;
  } catch {
    host = '';
  }

  return (
    <div
      className="group flex cursor-pointer flex-col gap-3.5 rounded-[20px] bg-white p-6 shadow-[0_24px_40px_rgba(0,31,42,0.06)] transition-all hover:-translate-y-0.5 hover:shadow-[0_6px_20px_rgba(0,31,42,0.08)] active:scale-[0.98]"
      onClick={() => onClick(company.company_name)}
    >
      <div className="flex items-start justify-between gap-2">
        <div className="min-w-0 flex-1">
          <h2
            className="truncate text-[22px] leading-tight font-black tracking-[-0.02em] text-[#001f2a]"
            title={company.company_name}
          >
            {company.company_name}
          </h2>
          {company.company_type && (
            <span className="mt-1 block text-[11px] font-bold tracking-wider text-[#434653]">
              {company.company_type}
            </span>
          )}
        </div>
        <div className="shrink-0 text-right">
          <div
            className="leading-none font-black tracking-[-0.02em] text-[#003d92] tabular-nums"
            style={{ fontSize: '1.75rem' }}
          >
            {company.job_count}
          </div>
          <div className="mt-0.5 text-[11px] text-[#434653]">個職缺</div>
        </div>
      </div>

      {company.keyword_groups.length > 0 && (
        <div className="space-y-2">
          {groupedKeywordGroups.map(group => (
            <div key={group.label}>
              <div className="mb-1.5 text-[10px] font-bold tracking-[0.15em] text-[#434653]">
                {group.label}
              </div>
              <div className="flex flex-wrap gap-1">
                {group.items.map(kg => (
                  <span
                    key={kg}
                    className={`rounded px-2 py-0.5 text-xs font-bold transition-colors ${
                      selectedSet.has(kg)
                        ? 'bg-[#003d92]/15 text-[#003d92]'
                        : 'bg-[#c9e7f7] text-[#434653]'
                    }`}
                  >
                    {labelMap.get(kg) ?? kg}
                  </span>
                ))}
                {group.remaining > 0 && (
                  <span className="px-1 py-0.5 text-xs font-bold text-[#434653]/60">
                    +{group.remaining}
                  </span>
                )}
              </div>
            </div>
          ))}
        </div>
      )}

      <div className="mt-auto flex items-center justify-between pt-2">
        <span className="flex items-center gap-1 text-xs font-bold text-[#003d92] opacity-0 transition-opacity group-hover:opacity-100">
          查看職缺 →
        </span>
        {company.company_link && (
          <a
            href={company.company_link}
            target="_blank"
            rel="noopener noreferrer"
            className="flex items-center gap-0.5 text-[11px] text-[#434653] hover:text-[#003d92]"
            onClick={e => e.stopPropagation()}
          >
            {host}
            <span
              className="material-symbols-outlined"
              style={{ fontSize: '12px' }}
            >
              open_in_new
            </span>
          </a>
        )}
      </div>
    </div>
  );
}

// apps/frontend/src/features/company/components/CompanyCard.vue
<script setup lang="ts">
import { computed } from 'vue';

import { SupabaseView } from '@codeshore/data-types';

interface Props {
  company: SupabaseView.MvCompany;
  keywordGroups: SupabaseView.MvKeywordGroup[];
  categoryLabelMap: Record<string, string>;
  selectedKeywordGroups?: string[];
}

const props = withDefaults(defineProps<Props>(), {
  selectedKeywordGroups: () => [],
});

const emit = defineEmits<{
  (e: 'click', companyName: string): void;
}>();

const CATEGORY_PRIORITY: Record<string, number> = {
  language: 0,
  framework: 1,
  database: 2,
  library: 3,
  service: 4,
  tool: 5,
};

const kgCategoryMap = computed(() => {
  const map = new Map<string, string>();
  for (const m of props.keywordGroups) {
    map.set(m.keyword_group, m.category ?? '');
  }
  return map;
});

const kgLabelMap = computed(() => {
  const map = new Map<string, string>();
  for (const m of props.keywordGroups) {
    map.set(m.keyword_group, m.label);
  }
  return map;
});

const kgCountMap = computed(() => {
  const map = new Map<string, number>();
  for (const m of props.keywordGroups) {
    map.set(m.keyword_group, m.count);
  }
  return map;
});

const selectedKeywordGroupsSet = computed(
  () => new Set(props.selectedKeywordGroups),
);

const groupedKeywordGroups = computed(() => {
  const buckets = new Map<string, string[]>();
  for (const kg of props.company.keyword_groups) {
    const raw = kgCategoryMap.value.get(kg) ?? '';
    const cat = raw in CATEGORY_PRIORITY ? raw : '';
    if (!buckets.has(cat)) buckets.set(cat, []);
    buckets.get(cat)!.push(kg);
  }
  return [...buckets.entries()]
    .sort(
      ([a], [b]) =>
        (CATEGORY_PRIORITY[a] ?? 6) -
        (CATEGORY_PRIORITY[b] ?? 6),
    )
    .map(([cat, items]) => {
      const sorted = [...items].sort(
        (a, b) =>
          (kgCountMap.value.get(b) ?? 0) -
          (kgCountMap.value.get(a) ?? 0),
      );
      return {
        label: props.categoryLabelMap[cat] ?? '其他',
        items: sorted.slice(0, 5),
        remaining: Math.max(0, sorted.length - 5),
      };
    });
});

const link = computed(
  () => new URL(props.company.company_link).host,
);
</script>

<template>
  <div
    class="group flex cursor-pointer flex-col gap-3.5 rounded-[20px] bg-white p-6 shadow-[0_24px_40px_rgba(0,31,42,0.06)] transition-all hover:-translate-y-0.5 hover:shadow-[0_6px_20px_rgba(0,31,42,0.08)] active:scale-[0.98]"
    @click="emit('click', company.company_name)"
  >
    <!-- Header: name + job count -->
    <div class="flex items-start justify-between gap-2">
      <div class="min-w-0 flex-1">
        <h2
          class="truncate text-[22px] leading-tight font-black tracking-[-0.02em] text-[#001f2a]"
          :title="company.company_name"
        >
          {{ company.company_name }}
        </h2>
        <span
          v-if="company.company_type"
          class="mt-1 block text-[11px] font-bold tracking-wider text-[#434653]"
        >
          {{ company.company_type }}
        </span>
      </div>
      <div class="shrink-0 text-right">
        <div
          class="leading-none font-black tracking-[-0.02em] text-[#003d92] tabular-nums"
          style="font-size: 1.75rem"
        >
          {{ company.job_count }}
        </div>
        <div class="mt-0.5 text-[11px] text-[#434653]">
          個職缺
        </div>
      </div>
    </div>

    <!-- Keyword groups by category -->
    <div
      v-if="company.keyword_groups.length > 0"
      class="space-y-2"
    >
      <div
        v-for="group in groupedKeywordGroups"
        :key="group.label"
      >
        <div
          class="mb-1.5 text-[10px] font-bold tracking-[0.15em] text-[#434653]"
        >
          {{ group.label }}
        </div>
        <div class="flex flex-wrap gap-1">
          <span
            v-for="kg in group.items"
            :key="kg"
            class="rounded px-2 py-0.5 text-xs font-bold transition-colors"
            :class="
              selectedKeywordGroupsSet.has(kg)
                ? 'bg-[#003d92]/15 text-[#003d92]'
                : 'bg-[#c9e7f7] text-[#434653]'
            "
            >{{ kgLabelMap.get(kg) ?? kg }}</span
          >
          <span
            v-if="group.remaining > 0"
            class="px-1 py-0.5 text-xs font-bold text-[#434653]/60"
            >+{{ group.remaining }}</span
          >
        </div>
      </div>
    </div>

    <!-- Footer CTA -->
    <div
      class="mt-auto flex items-center justify-between pt-2"
    >
      <span
        class="flex items-center gap-1 text-xs font-bold text-[#003d92] opacity-0 transition-opacity group-hover:opacity-100"
      >
        查看職缺 →
      </span>
      <a
        v-if="company.company_link"
        :href="company.company_link"
        target="_blank"
        rel="noopener noreferrer"
        class="flex items-center gap-0.5 text-[11px] text-[#434653] hover:text-[#003d92]"
        @click.stop
      >
        {{ link }}
        <span
          class="material-symbols-outlined"
          style="font-size: 12px"
          >open_in_new</span
        >
      </a>
    </div>
  </div>
</template>
