// apps/frontend/src/features/job/components/JobList.tsx
import { useEffect, useRef } from 'react';

import { SupabaseView } from '@codeshore/data-types';

import { Pagination } from '../../../components/Pagination';
import { usePreferenceMutation } from '../mutations';
import { JOB_PAGE_SIZE } from '../queries';
import { JobDetailDrawer } from './JobDetailDrawer';
import { JobListItem } from './JobListItem';
import { JobListSkeleton } from './JobListSkeleton';

interface JobListProps {
  jobs: SupabaseView.MvJob[];
  count: number;
  page: number;
  loading: boolean;
  fetching: boolean;
  listViewPreference: 'like' | 'dislike' | null;
  selectedJobId: string | null;
  hasActiveFilters: boolean;
  onSelectJob: (jobId: string | null) => void;
  onPageChange: (page: number) => void;
  onClearAllFilters: () => void;
}

// Job list + pagination + detail drawer orchestration (task 7.5),
// ported from JobList.vue. Server data arrives via props (TanStack Query);
// the optimistic like/dislike mutation lives here so the list item buttons
// and the drawer share one instance.
export function JobList({
  jobs,
  count,
  page,
  loading,
  fetching,
  listViewPreference,
  selectedJobId,
  hasActiveFilters,
  onSelectJob,
  onPageChange,
  onClearAllFilters,
}: JobListProps) {
  const preferenceMutation = usePreferenceMutation();
  const totalPages = Math.ceil(count / JOB_PAGE_SIZE);

  const selectedJob = jobs.find(x => x.id === selectedJobId);
  const selectedJobIndex = jobs.findIndex(x => x.id === selectedJobId);
  const isFirstJobOnFirstPage = selectedJobIndex === 0 && page === 1;
  const isLastJobOnLastPage =
    selectedJobIndex === jobs.length - 1 && page >= totalPages;

  // Cross-page drawer navigation: when we step past the current page, remember
  // which end of the next page to land on, then apply it once it loads.
  const pendingSelect = useRef<'first' | 'last' | null>(null);
  useEffect(() => {
    if (!pendingSelect.current || fetching || jobs.length === 0) return;
    const target =
      pendingSelect.current === 'first'
        ? jobs[0]?.id
        : jobs[jobs.length - 1]?.id;
    pendingSelect.current = null;
    onSelectJob(target ?? null);
  }, [jobs, fetching, onSelectJob]);

  const goToPrevJob = () => {
    if (isFirstJobOnFirstPage || fetching) return;
    if (selectedJobIndex > 0) {
      onSelectJob(jobs[selectedJobIndex - 1].id);
    } else {
      pendingSelect.current = 'last';
      onPageChange(page - 1);
    }
  };

  const goToNextJob = () => {
    if (isLastJobOnLastPage || fetching) return;
    if (selectedJobIndex < jobs.length - 1) {
      onSelectJob(jobs[selectedJobIndex + 1].id);
    } else {
      pendingSelect.current = 'first';
      onPageChange(page + 1);
    }
  };

  const updatePreference = (preference: 'like' | 'dislike') => {
    if (preferenceMutation.isPending || !selectedJob) return;
    const currentId = selectedJob.id;
    const currentIndex = selectedJobIndex;
    const nextJob =
      jobs[currentIndex + 1] ?? jobs[currentIndex - 1] ?? null;
    onSelectJob(nextJob?.id ?? null);
    preferenceMutation.mutate({ id: currentId, preference });
  };

  const onPreference = (id: string, preference: 'like' | 'dislike') => {
    preferenceMutation.mutate({ id, preference });
  };

  // Keep the selected row visible as the drawer steps through jobs.
  const itemElMap = useRef(new Map<string, HTMLLIElement>());
  useEffect(() => {
    if (selectedJobId) {
      itemElMap.current
        .get(selectedJobId)
        ?.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
    }
  }, [selectedJobId]);

  return (
    <>
      <div className="overflow-hidden rounded-xl bg-white shadow-[0_24px_40px_rgba(0,31,42,0.06)]">
        {loading ? (
          <JobListSkeleton />
        ) : jobs.length === 0 ? (
          <div className="flex flex-col items-center justify-center p-12 text-center">
            <span className="material-symbols-outlined mb-4 text-6xl text-[#001f2a]/20">
              search_off
            </span>
            <h2 className="mb-2 text-xl font-black text-[#001f2a]">
              此篩選條件沒有職缺
            </h2>
            <p className="mb-6 text-sm text-[#434653]">
              試試切換別的篩選組合或清空篩選條件，以探索更多機會。
            </p>
            {hasActiveFilters && (
              <button
                type="button"
                className="cursor-pointer rounded-xl bg-[#003d92] px-6 py-2 text-sm font-bold text-white transition-colors hover:bg-[#1654b9] active:scale-95"
                onClick={onClearAllFilters}
              >
                清空所有篩選
              </button>
            )}
          </div>
        ) : (
          <>
            <ul className="divide-y divide-[#001f2a]/[0.06] pl-0">
              {jobs.map(job => (
                <JobListItem
                  key={job.id}
                  innerRef={el => {
                    if (el) itemElMap.current.set(job.id, el);
                    else itemElMap.current.delete(job.id);
                  }}
                  job={job}
                  selected={selectedJobId === job.id}
                  listViewPreference={listViewPreference}
                  disabled={fetching}
                  onSelect={onSelectJob}
                  onPreference={onPreference}
                />
              ))}
            </ul>

            {totalPages > 1 && (
              <div className="border-t border-[#001f2a]/[0.06] px-5 py-3">
                <span className="mb-2 block text-xs font-bold text-[#434653]">
                  第 {page} / {totalPages} 頁・共 {count} 筆
                </span>
                <Pagination
                  currentPage={page}
                  totalPages={totalPages}
                  onPageChange={onPageChange}
                />
              </div>
            )}
          </>
        )}
      </div>

      <JobDetailDrawer
        job={selectedJob}
        isFirst={isFirstJobOnFirstPage}
        isLast={isLastJobOnLastPage}
        loading={loading}
        preferenceUpdating={preferenceMutation.isPending}
        listViewPreference={listViewPreference}
        onClose={() => onSelectJob(null)}
        onPrev={goToPrevJob}
        onNext={goToNextJob}
        onUpdatePreference={updatePreference}
      />
    </>
  );
}

// apps/frontend/src/features/job/components/JobList.vue
<script lang="ts" setup>
import { computed, nextTick, watch } from 'vue';

import Pagination from '../../../components/Pagination.vue';
import { useJobStore } from '../useJobStore';
import JobDetailDrawer from './JobDetailDrawer.vue';
import JobListItem from './JobListItem.vue';
import JobListSkeleton from './JobListSkeleton.vue';

type Props = { hasActiveFilters: boolean };
const props = withDefaults(defineProps<Props>(), {
  hasActiveFilters: false,
});

type Emits = { (e: 'clearAllFilters'): void };
const emit = defineEmits<Emits>();

const store = useJobStore();

const selectedJobId = defineModel<string | null>('selectedJobId', { default: null });
const selectedJob = computed(() => store.listJobs.find(x => x.id === selectedJobId.value));

const totalPages = computed(() =>
  Math.ceil(store.listTotalCount / store.listPageSize),
);

const selectedJobIndex = computed(() =>
  store.listJobs.findIndex(x => x.id === selectedJobId.value),
);

const isFirstJobOnFirstPage = computed(
  () => selectedJobIndex.value === 0 && store.listPage === 1,
);

const isLastJobOnLastPage = computed(
  () =>
    selectedJobIndex.value === store.listJobs.length - 1 &&
    store.listPage >= totalPages.value,
);

const goToPage = async (page: number) => {
  if (page < 1 || page > totalPages.value || store.loading) return;
  await store.fetchListJobs({
    preference: store.listViewPreference!,
    page,
    loadingEffect: true,
  });
};

const goToPrevJob = async () => {
  if (isFirstJobOnFirstPage.value || store.loading) return;
  if (selectedJobIndex.value > 0) {
    selectedJobId.value = store.listJobs[selectedJobIndex.value - 1].id;
  } else {
    await store.fetchListJobs({
      preference: store.listViewPreference!,
      page: store.listPage - 1,
      loadingEffect: true,
    });
    selectedJobId.value = store.listJobs[store.listJobs.length - 1]?.id ?? null;
  }
};

const goToNextJob = async () => {
  if (isLastJobOnLastPage.value || store.loading) return;
  if (selectedJobIndex.value < store.listJobs.length - 1) {
    selectedJobId.value = store.listJobs[selectedJobIndex.value + 1].id;
  } else {
    await store.fetchListJobs({
      preference: store.listViewPreference!,
      page: store.listPage + 1,
      loadingEffect: true,
    });
    selectedJobId.value = store.listJobs[0]?.id ?? null;
  }
};

const updatePreference = (preference: 'like' | 'dislike') => {
  if (store.preferenceUpdating) return;
  const currentId = selectedJob.value!.id;
  const currentIndex = selectedJobIndex.value;

  // Immediately show the next job without waiting for the API
  const nextJob =
    store.listJobs[currentIndex + 1] ??
    store.listJobs[currentIndex - 1] ??
    null;
  selectedJobId.value = nextJob?.id ?? null;

  // Background update — does not block the UI
  store.updateListJobPreference(currentId, preference);
};

const listItemElMap = new Map<string, HTMLElement>();

const setListItemRef = (el: unknown, jobId: string) => {
  if (el) {
    listItemElMap.set(jobId, (el as { $el: HTMLElement }).$el);
  } else {
    listItemElMap.delete(jobId);
  }
};

watch(selectedJobId, async newId => {
  await nextTick();
  if (newId) {
    listItemElMap.get(newId)?.scrollIntoView({
      behavior: 'smooth',
      block: 'nearest',
    });
  }
});
</script>

<template>
  <div class="overflow-hidden rounded-xl bg-white shadow-[0_24px_40px_rgba(0,31,42,0.06)]">
    <JobListSkeleton v-if="store.loading" />

    <div
      v-else-if="store.listJobs.length === 0"
      class="flex flex-col items-center justify-center p-12 text-center"
    >
      <span class="material-symbols-outlined mb-4 text-6xl text-[#001f2a]/20">search_off</span>
      <h2 class="mb-2 text-xl font-black text-[#001f2a]">此篩選條件沒有職缺</h2>
      <p class="mb-6 text-sm text-[#434653]">
        試試切換別的篩選組合或清空篩選條件，以探索更多機會。
      </p>
      <button
        v-if="props.hasActiveFilters"
        class="cursor-pointer rounded-xl bg-[#003d92] px-6 py-2 text-sm font-bold text-white transition-colors hover:bg-[#1654b9] active:scale-95"
        @click="emit('clearAllFilters')"
      >
        清空所有篩選
      </button>
    </div>

    <template v-else>
      <ul class="divide-y divide-[#001f2a]/[0.06] pl-0">
        <JobListItem
          v-for="job in store.listJobs"
          :key="job.id"
          :ref="el => setListItemRef(el, job.id)"
          :job="job"
          :selected="selectedJobId === job.id"
          @select="selectedJobId = $event"
        />
      </ul>

      <div
        v-if="totalPages > 1"
        class="border-t border-[#001f2a]/[0.06] px-5 py-3"
      >
        <span class="mb-2 block text-xs font-bold text-[#434653]">
          第 {{ store.listPage }} / {{ totalPages }} 頁・共 {{ store.listTotalCount }} 筆
        </span>
        <Pagination
          :current-page="store.listPage"
          :total-pages="totalPages"
          @update:current-page="goToPage"
        />
      </div>
    </template>
  </div>

  <JobDetailDrawer
    :job="selectedJob"
    :is-first="isFirstJobOnFirstPage"
    :is-last="isLastJobOnLastPage"
    @close="selectedJobId = null"
    @prev="goToPrevJob"
    @next="goToNextJob"
    @update-preference="updatePreference"
  />
</template>
